/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */

pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
    // TODO: take an oauth2 token source, similar to the go one
}

pub type BasicAuth = (String, Option<String>);

pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new(base_path: String) -> Configuration {
        Configuration {
            base_path,
            user_agent: Some("OpenAPI-Generator/1.9.0/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            api_key: None,
        }
    }

    pub fn with_basic_auth(
        base_path: String,
        username: String,
        password: Option<String>,
    ) -> Configuration {
        Configuration {
            base_path,
            user_agent: Some("OpenAPI-Generator/1.9.0/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: Some((username, password)),
            oauth_access_token: None,
            api_key: None,
        }
    }

    pub fn with_oauth_access_token(base_path: String, access_token: String) -> Configuration {
        Configuration {
            base_path,
            user_agent: Some("OpenAPI-Generator/1.9.0/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: Some(access_token),
            api_key: None,
        }
    }

    pub fn with_api_key(base_path: String, api_key: ApiKey) -> Configuration {
        Configuration {
            base_path,
            user_agent: Some("OpenAPI-Generator/1.9.0/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            api_key: Some(api_key),
        }
    }
}
