/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ApplicationSignOnMode {
    Bookmark,
    BasicAuth,
    BrowserPlugin,
    SecurePasswordStore,
    AutoLogin,
    WsFederation,
    #[serde(rename = "SAML_2_0")]
    Saml2_0,
    OpenidConnect,
    #[serde(rename = "SAML_1_1")]
    Saml1_1,
}
