/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApplicationLicensing {
  #[serde(rename = "seatCount")]
  seat_count: Option<i32>
}

impl ApplicationLicensing {
  pub fn new() -> ApplicationLicensing {
    ApplicationLicensing {
      seat_count: None
    }
  }

  pub fn set_seat_count(&mut self, seat_count: i32) {
    self.seat_count = Some(seat_count);
  }

  pub fn with_seat_count(mut self, seat_count: i32) -> ApplicationLicensing {
    self.seat_count = Some(seat_count);
    self
  }

  pub fn seat_count(&self) -> Option<&i32> {
    self.seat_count.as_ref()
  }

  pub fn reset_seat_count(&mut self) {
    self.seat_count = None;
  }

}



