/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BasicApplicationSettingsApplication {
  #[serde(rename = "authURL")]
  auth_url: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl BasicApplicationSettingsApplication {
  pub fn new() -> BasicApplicationSettingsApplication {
    BasicApplicationSettingsApplication {
      auth_url: None,
      url: None
    }
  }

  pub fn set_auth_url(&mut self, auth_url: String) {
    self.auth_url = Some(auth_url);
  }

  pub fn with_auth_url(mut self, auth_url: String) -> BasicApplicationSettingsApplication {
    self.auth_url = Some(auth_url);
    self
  }

  pub fn auth_url(&self) -> Option<&String> {
    self.auth_url.as_ref()
  }

  pub fn reset_auth_url(&mut self) {
    self.auth_url = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> BasicApplicationSettingsApplication {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



