/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BasicApplicationSettings {
  #[serde(rename = "app")]
  app: Option<crate::models::BasicApplicationSettingsApplication>
}

impl BasicApplicationSettings {
  pub fn new() -> BasicApplicationSettings {
    BasicApplicationSettings {
      app: None
    }
  }

  pub fn set_app(&mut self, app: crate::models::BasicApplicationSettingsApplication) {
    self.app = Some(app);
  }

  pub fn with_app(mut self, app: crate::models::BasicApplicationSettingsApplication) -> BasicApplicationSettings {
    self.app = Some(app);
    self
  }

  pub fn app(&self) -> Option<&crate::models::BasicApplicationSettingsApplication> {
    self.app.as_ref()
  }

  pub fn reset_app(&mut self) {
    self.app = None;
  }

}



