/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BrowserPluginApplication {
  #[serde(rename = "credentials")]
  credentials: Option<crate::models::SchemeApplicationCredentials>
}

impl BrowserPluginApplication {
  pub fn new() -> BrowserPluginApplication {
    BrowserPluginApplication {
      credentials: None
    }
  }

  pub fn set_credentials(&mut self, credentials: crate::models::SchemeApplicationCredentials) {
    self.credentials = Some(credentials);
  }

  pub fn with_credentials(mut self, credentials: crate::models::SchemeApplicationCredentials) -> BrowserPluginApplication {
    self.credentials = Some(credentials);
    self
  }

  pub fn credentials(&self) -> Option<&crate::models::SchemeApplicationCredentials> {
    self.credentials.as_ref()
  }

  pub fn reset_credentials(&mut self) {
    self.credentials = None;
  }

}



