/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EmailFactor {
  #[serde(rename = "profile")]
  profile: Option<crate::models::EmailFactorProfile>
}

impl EmailFactor {
  pub fn new() -> EmailFactor {
    EmailFactor {
      profile: None
    }
  }

  pub fn set_profile(&mut self, profile: crate::models::EmailFactorProfile) {
    self.profile = Some(profile);
  }

  pub fn with_profile(mut self, profile: crate::models::EmailFactorProfile) -> EmailFactor {
    self.profile = Some(profile);
    self
  }

  pub fn profile(&self) -> Option<&crate::models::EmailFactorProfile> {
    self.profile.as_ref()
  }

  pub fn reset_profile(&mut self) {
    self.profile = None;
  }

}



