/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FactorStatus {
}

impl FactorStatus {
  pub fn new() -> FactorStatus {
    FactorStatus {
    }
  }

}

// TODO enum 
// List of FactorStatus
//const (
//  
//  
//  
//)


