/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FactorType {
    Push,
    Sms,
    Call,
    Token,
    #[serde(rename = "token:software:totp")]
    TotpSoftwareToken,
    #[serde(rename = "token:hardware")]
    HardwareToken,
    Question,
    Web,
    Email,
    U2f,
    Webauthn,
    #[serde(rename = "token:software")]
    SoftwareToken,
    Custom,
}
