/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct LogSeverity {
}

impl LogSeverity {
  pub fn new() -> LogSeverity {
    LogSeverity {
    }
  }

}

// TODO enum 
// List of LogSeverity
//const (
//  
//  
//  
//)


