/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OAuthApplicationCredentials {
  #[serde(rename = "oauthClient")]
  oauth_client: Option<crate::models::ApplicationCredentialsOAuthClient>
}

impl OAuthApplicationCredentials {
  pub fn new() -> OAuthApplicationCredentials {
    OAuthApplicationCredentials {
      oauth_client: None
    }
  }

  pub fn set_oauth_client(&mut self, oauth_client: crate::models::ApplicationCredentialsOAuthClient) {
    self.oauth_client = Some(oauth_client);
  }

  pub fn with_oauth_client(mut self, oauth_client: crate::models::ApplicationCredentialsOAuthClient) -> OAuthApplicationCredentials {
    self.oauth_client = Some(oauth_client);
    self
  }

  pub fn oauth_client(&self) -> Option<&crate::models::ApplicationCredentialsOAuthClient> {
    self.oauth_client.as_ref()
  }

  pub fn reset_oauth_client(&mut self) {
    self.oauth_client = None;
  }

}



