/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PasswordPolicyConditions {
  #[serde(rename = "authProvider")]
  auth_provider: Option<crate::models::PasswordPolicyAuthenticationProviderCondition>,
  #[serde(rename = "people")]
  people: Option<crate::models::PolicyPeopleCondition>
}

impl PasswordPolicyConditions {
  pub fn new() -> PasswordPolicyConditions {
    PasswordPolicyConditions {
      auth_provider: None,
      people: None
    }
  }

  pub fn set_auth_provider(&mut self, auth_provider: crate::models::PasswordPolicyAuthenticationProviderCondition) {
    self.auth_provider = Some(auth_provider);
  }

  pub fn with_auth_provider(mut self, auth_provider: crate::models::PasswordPolicyAuthenticationProviderCondition) -> PasswordPolicyConditions {
    self.auth_provider = Some(auth_provider);
    self
  }

  pub fn auth_provider(&self) -> Option<&crate::models::PasswordPolicyAuthenticationProviderCondition> {
    self.auth_provider.as_ref()
  }

  pub fn reset_auth_provider(&mut self) {
    self.auth_provider = None;
  }

  pub fn set_people(&mut self, people: crate::models::PolicyPeopleCondition) {
    self.people = Some(people);
  }

  pub fn with_people(mut self, people: crate::models::PolicyPeopleCondition) -> PasswordPolicyConditions {
    self.people = Some(people);
    self
  }

  pub fn people(&self) -> Option<&crate::models::PolicyPeopleCondition> {
    self.people.as_ref()
  }

  pub fn reset_people(&mut self) {
    self.people = None;
  }

}



