/* 
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.9.0
 * Contact: devex-public@okta.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PasswordPolicyRecoveryQuestionComplexity {
  #[serde(rename = "minLength")]
  min_length: Option<i32>
}

impl PasswordPolicyRecoveryQuestionComplexity {
  pub fn new() -> PasswordPolicyRecoveryQuestionComplexity {
    PasswordPolicyRecoveryQuestionComplexity {
      min_length: None
    }
  }

  pub fn set_min_length(&mut self, min_length: i32) {
    self.min_length = Some(min_length);
  }

  pub fn with_min_length(mut self, min_length: i32) -> PasswordPolicyRecoveryQuestionComplexity {
    self.min_length = Some(min_length);
    self
  }

  pub fn min_length(&self) -> Option<&i32> {
    self.min_length.as_ref()
  }

  pub fn reset_min_length(&mut self) {
    self.min_length = None;
  }

}



